[theme]
primaryColor = "#2DD4BF"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#001716"
textColor = "#F8FAFC"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme.colors]
primary = "#2DD4BF"
primaryHover = "#5EEAD4"
primaryActive = "#14B8A6"
secondary = "#8B5CF6"
secondaryHover = "#A78BFA"
secondaryActive = "#7C3AED"
text = "#F8FAFC"
textLight = "#CBD5E1"
textDark = "#0F172A"

[theme.typography]
font = "geist"
fontSize = "1rem"
fontSizeSmall = "0.875rem"
fontSizeLarge = "1.25rem"
monospace = "monospace"
fontUrl = "static/Geist-Regular.ttf"

[theme.fontFaces]
family="geist"
url="static/Geist-Regular.ttf"
style="Regular"

[theme.spacing]
base = "1rem"
small = "0.5rem"
large = "2rem"

[theme.radius]
base = "0.5rem"
small = "0.25rem"
large = "1rem" 